// Add your dependencies here

dependencies {
    api("com.github.GTNewHorizons:GTNHLib:0.10.8:dev")
    api("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev")
    api("com.github.GTNewHorizons:Baubles-Expanded:2.2.21-GTNH:dev")

    compileOnly("com.github.GTNewHorizons:BloodMagic:1.9.4:dev")
    compileOnly("com.github.GTNewHorizons:Botania:1.13.21-GTNH:api")
    compileOnly("com.github.GTNewHorizons:AppleCore:3.3.11:dev")
    compileOnly("curse.maven:ee3-65509:2305023")

    runtimeOnlyNonPublishable("com.github.GTNewHorizons:AspectRecipeIndex:1.1.0:dev")
}
